name: sew_ml
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  file_picker: ^10.1.3
  flutter:
    sdk: flutter
  open_dir: ^0.0.2+1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  petitparser: ^6.0.2
  re_editor: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  vector_math: ^2.1.4

flutter:
  uses-material-design: true
